# Generated by Django 5.1.2 on 2024-12-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_42',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
