# Generated by Django 5.1.2 on 2024-12-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_avatar_42'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_42',
        ),
    ]
