# Generated by Django 5.1.2 on 2025-01-08 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_x', models.FloatField(default=400)),
                ('ball_y', models.FloatField(default=300)),
                ('ball_speed_x', models.FloatField(default=0.3)),
                ('ball_speed_y', models.FloatField(default=0.3)),
                ('left_paddle_y', models.IntegerField(default=250)),
                ('right_paddle_y', models.IntegerField(default=250)),
                ('left_score', models.IntegerField(default=0)),
                ('right_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('right_actif', models.BooleanField(default=False)),
                ('left_actif', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('game_type', models.CharField(choices=[('local', 'Local Game'), ('online', 'Online Game')], default='local', max_length=10)),
                ('player_left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_left', to=settings.AUTH_USER_MODEL)),
                ('player_right', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_right', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
