# Generated by Django 5.1.2 on 2025-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='ball_speed_x',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='ball_speed_y',
            field=models.FloatField(default=0.8),
        ),
    ]
